/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may be overwritten.
 *
 * @generated by codegen
 */
'use strict';

import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';

export interface Spec extends TurboModule {
  add(a: number, b: number): Promise<number>;
}

export default (undefined: ?Spec);
