package com.testcpp

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.turbomodule.core.interfaces.TurboModule

import com.testcpp.NativeAdderSpec // This will be generated by Codegen

class NativeAdderModule(context: ReactApplicationContext) : NativeAdderSpec(context) {

  override fun getName(): String = "NativeAdder"

  override fun add(a: Double, b: Double, promise: Promise) {
    promise.resolve(nativeAdd(a, b))
  }

  private external fun nativeAdd(a: Double, b: Double): Double

  companion object {
    init {
      System.loadLibrary("cppintegration")
    }
  }
}
